### ISSUE TITLE
Select operation mode in the App

### ISSUE THREAD

**Issue by jfmcarreira** [Forceu/barcodebuddy-android#1]
It would be useful to be able to select the operation mode I the app. For instance a drop down menu.

Great job with barcode buddy. I am starting with grocy and this companion app makes it much easier to work with.

Thanks for the great job.

**Comment by Forceu** [comment]
Thank you for your feedback! Yes, that is already on my todo list and will be added in the next version :)

**Comment by hmronline** [comment]
This feature will greatly improve the ease of use and therefore family adoption for daily usage. Looking forward for the next version!

**Comment by barrelltitor** [comment]
Any updates on this? Without being able to add a product by scanning it, the app can only be used for new products or consuming products unfortunately

**Comment by Forceu** [comment]
Sorry for the delay on this, unfortunately I have very little time at the moment, but I would be more than happy to merge a pull request if someone else implements it.

**Comment by Forceu** [comment]
Added in 454232b
