### ISSUE TITLE
Fastlane structure is broken

### ISSUE THREAD

**Issue by IzzySoft** [Forceu/barcodebuddy-android#10]
Your app is now available at F-Droid – but without summary, without description etc as your current Fastlane structure is broken.

* You now have: `fastlane/metadata/en-US`
* You should have: `fastlane/metadata/android/en-US`

Can you please correct that and tag a new release, so descriptions are shown on F-Droid? Thanks!

**Comment by Forceu** [comment]
Thanks a lot for bringing it to my attention! It has been fixed in c90206f4422f54d6b449169b5d2b8b5460cdf7d6

**Comment by IzzySoft** [comment]
Thanks, that was fast! As F-Droid only picks that with the build: when is the next release planned?

**Comment by Forceu** [comment]
I already did a release so it gets triggered ;)
Again, thanks a lot for all your help!

**Comment by IzzySoft** [comment]
Oh, apologies – I should have checked before asking :laughing: Thanks!
