### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Forceu/barcodebuddy-android#11]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by Forceu** [comment]
Thanks, I will add it to the next release!

**Comment by mondlicht-und-sterne** [comment]
thank you that would be nice

After that, the issue can also be closed
