### ISSUE TITLE
Making use of Android Vision

### ISSUE THREAD

**Issue by fan1200** [Forceu/barcodebuddy-android#12]
Hi! As I was testing out the app it couldn't really scan any barcode unless you have good lighting and good focus. I saw that the app relies on the zxing package which doesn't make the most out of your app. I played with this idea a few weeks back and came across the Android Vision project. Although being not maintained anymore it still works with some modifications regarding full screen scanning. After a modified library I was able to scan barcodes in a matter of a second without having to worry too much about lighting and focus. I could highly recommend you to look into it and ultimately replacing the zxing package.

You could use the following library: https://github.com/ravi8x/Barcode-Reader

A known issue is that camera is zoomed by default but this can easily be fixed by downloading the library yourself and fix it with the following comment: https://github.com/ravi8x/Barcode-Reader/issues/8#issuecomment-352672685

**Comment by Forceu** [comment]
Thank you for your suggestion! Unfortunately it uses Google Play Services, which I try to avoid. I will have a look at alternatives though!
