### ISSUE TITLE
Error: Server Error

### ISSUE THREAD

**Issue by horphi0815** [Forceu/barcodebuddy-android#14]
Hello,

thanks for this great feature. :-)

I have a small problem. After successful connect i try to scan a barcode:
The Error appears --> "Error: Server Error"

Are there some Logs i can review for this error?

Best regards,

Phil

**Comment by Forceu** [comment]
Hi Phil, unfortunately I need more information, eg. what version / webserver / PHP version you are running, where the error comes up and if possible a screenshot.

**Comment by horphi0815** [comment]
Hi, @Forceu 

thx for your reply.
Please close this issue. It was a proxy problem.
Issue is solved.
Thx for yur fast support. :-)

BR

Phil

**Comment by Forceu** [comment]
Alright, good to hear :)
