### ISSUE TITLE
[Android App] Bluetooth Barcode Scanner escaping ":"

### ISSUE THREAD

**Issue by gthbusrr** [Forceu/barcodebuddy-android#20]
When I connect a barcode scanner to my android device via bluetooth and scan a **grocycode** (`grcy:p:xxx`), barcode buddy will read `GRCYPXXX` instead, escaping all colons `:`.

However, when I instead select an open text field on my phone (other app), the colon `:` was preserved.

**Comment by Forceu** [comment]
Thanks, I will have a look at it in the next days!

**Comment by jeremy-parks01** [comment]
@Forceu  
Thank you for the quick response.  To further test I sent some test payloads to the BarcodeBuddy API through Postman and those requests with the colon are being handled properly.   I think this is specifically related to the Android app and is note in this [Bug](https://github.com/Forceu/barcodebuddy-android/issues/20). I am not much of a Java developer but I will have a look as well.
