### ISSUE TITLE
Android App: 0.4.1 on F-Droid 

### ISSUE THREAD

**Issue by OiledAmoeba** [Forceu/barcodebuddy-android#25]
PlayStore shows 0.4.1 from 27.08.2024
This Version is missing on F-Droid (last 0.4.0 from January)

**Comment by Forceu** [comment]
Thanks for the heads-up! This seems to be a problem with F-Droid, as the update has been received, but was not build. I will investigate the issue

**Comment by Forceu** [comment]
I could not find the root cause, I assume there was simply some delay with F-Droid. It has been published in the meantime however.
