### ISSUE TITLE
Android App Error: Unknown error occurred. Please check URL.

### ISSUE THREAD

**Issue by Lockszmith** [Forceu/barcodebuddy-android#4]
I'm a  brand new user to both gorcy and barcode buddy.

So first, before I start 'complaining' - I have to say - AMAZING work on barcodebuddy and it's android app. The clean design of this solution is really inspiring.

My Issue
======
Setting up
------------
(I think) I followed the instructions properly:
- grocy and barcodebuddy installed via docker-compose behind a traefik reverse proxy
- both grocy and bardcodebuddy are accessible via Let's Encrypt signed certificates HTTPS
- grocy is on
  > https://grocy.< mydomain >
- barcodebuddy is on
  > https://bcb.< mydomain >
- I've setup authentication for barcodebuddy and logged in
- connected to grocy's API. barcodebuddy setting page states:
   >   Successfully connected to Grocy, valid API key.
- in API, added Mobile App
- Installed official Google Play android app
- Scanned QR Code

All of the above was rather simple to follow, and everything seemed to be working smooth.

Problem
----------
I might be missing something, but now when I scan a barcode, I was expecting it to show in Unkown Barcodes or Processed, but instead in the Android App, I get the following error:
> Error: Unknown error occurred. Please check URL.
`* See screenshot below`

Question
----------
So I'm stuck at this point.
Is there a log I can check?
Anything in the process I'm missing?

### Screenshot
![Screenshot](https://i.imgur.com/gfq3KIgl.jpg)

**Comment by Forceu** [comment]
Hm that is weird, it could be related to the reverse proxy. Can you please install the attached version, and try again?

[app-debugPublic.zip](https://github.com/Forceu/barcodebuddy-android/files/4494093/app-debugPublic.zip)

**Comment by Lockszmith** [comment]
Just saw your reply, and tried the app.

Now something different is happening.
I'll describe the timeline, so you can see what I mean:

* I install the app-debugPublic.apk over already installed (and setup) app.
* Scan a bar code: ❗ 🎉 😄  **It shows up in Processed Barcodes** with the following message:
  >  2020-04-17 11:48:14: Unknown barcode could not be looked up. Barcode: #########
* I think to myself 🤔 , awesome! Let's make sure it's this apk and nothing else, so I uninstall and install again from Play store.
* Need to setup again, add mobile app, scan QR code, get to scanning a barcode again.
* As reported originally, get the Unknown error occurred (as expected ).
* Uninstall play store app. Install debug APK.
* Register the mobile app.
* Scan barcode - **app crashes** 😞.
* At this point I tried different orders of uninstalling/installing, the new APK crashes, the old one returns the Unknown error.

So... something different is happening with this APK, and for a second there it seemed to have worked, but then it crashes.

Any logs I can collect?

**Comment by Forceu** [comment]
Okay, that is indeed interesting... Please install the attached version and let me know if it is still crashing. If yes, it will give you the option to send the log to an email, please do that and also upload the file from the email to this issue.
[app-debugPublic.zip](https://github.com/Forceu/barcodebuddy-android/files/4505464/app-debugPublic.zip)

**Comment by 24hourbullshit** [comment]
I experience the same problem, tried the debug version, you should have the logs on email by now!

**Comment by Lockszmith** [comment]
@24hourbullshit - is your setup the same as mine?

**Comment by 24hourbullshit** [comment]
Barcode Buddy running via Docker and Grocy in Docker via Home Assistant.

BB is accessible from the "outside", Traefik acts as my middle man, Grocy in turn is accessible only internally at the moment, if I don't go via Home Assistant.

**Comment by Lockszmith** [comment]
I wonder what traefik does differently than (let's say) Ngnix - which is probably what @Forceu is using.

@Forceu - anyway you can create an APK that outputs the raw HTTP response?
I'll create another setup with Nginx and compare and we try and assess how traefik is different here.

**Comment by Lockszmith** [comment]
sorry, clicked by mistake :(

**Comment by Forceu** [comment]
Thanks, so I received the stacktrace and the debug apps seams to be crashing, because the response seems to be null (the debug version should basically show the raw response, as @Lockszmith suggested).

I also setup Traefik, however the app is working for me without any problems :/ I updated the debug version, so it doesn't crash anymore. Please try again with this version and post the output it displays in the debug window after scanning a barcode.

Can you maybe share your Traefik / Docker config so I can reproduce the problem?

[app-debugPublic.zip](https://github.com/Forceu/barcodebuddy-android/files/4515408/app-debugPublic.zip)

**Comment by Lockszmith** [comment]
Just sent the new crash-dump

**Comment by Forceu** [comment]
> Just sent the new crash-dump

It appears you are still using the old version, can you please double check that you installed the APK from the ZIP archive above? It has the same name, so maybe you chose wrong one.

Ah okay, I tried it with Traefik 2.2, maybe that is why.

**Comment by Lockszmith** [comment]
You are right! sorry about that.
Now I get:

> Received Body is null.
> Received Error Body:
>
> 'Temporary Redirect'

This is actually some sort of text-editing control, but there wasn't any button I could use to send/collect more details.

I also tried what you suggested with the latest-dev tag (awesome API testing page BTW, really well thought off), and the posting of a barcode works, multiple times with same or different data.
So it looks like curl is handling whatever traefik is throwing at it OK, but the android app (at least on barcode scanning) is choking on it. (maybe perform a test call when API registration happens, and collect data there?)

I tried curl with verbose output on the localmachine, on a remote one (outside of my home) and from the android phone, connected to home-wifi and with cell connection. The only response I got was 200, no redirection.

Hope you have an idea here.

**Comment by Forceu** [comment]
Thanks, that helps a lot! Normally the client should follow redirects automatically, so that is kind of surprising... Do you have any change from  HTTP to HTTPS?

Anyways, please try the attached version and let me know if it is working with that one.

[app-release.zip](https://github.com/Forceu/barcodebuddy-android/files/4518925/app-release.zip)

**Comment by Lockszmith** [comment]
I think I've completely wasted your time. And this whole ordeal was a classic [PEBKAC](http://ars.userfriendly.org/cartoons/?id=19980506)

When registering the mobile application, the page shows the URL, the API Key and the QR code.
By default it shows an **http** address, but it allows to edit the URL.

Inside the docker container, barcodebuddy is running as HTTP, it is the reverse-proxy that makes the connection HTTPS.

When I edited the address from http://bcb.example.com to https://bcb.example.com - the mobile client works without a problem.

I apologize for wasting your time, hope this issue will help others who made the same mistake I made.

![Remember the S in HTTPS](http://i.picasion.com/pic90/711941e67451c7ab57663d0105488da0.gif)

**Comment by Forceu** [comment]
Great to hear it is working now! And no worries, I did not realise that OkHttpClient does not honor HTTP to HTTPS redirects. I fixed it in https://github.com/Forceu/barcodebuddy-android/commit/2df2bb2c57ce4369cc87391f14db5835a87f46b2 and might add a note next to QR code if it is in HTTP

**Comment by 24hourbullshit** [comment]
I confirm, the problem was the same for me! Great that it was so easy to just add an "s", thanks for a greap app :)
