### ISSUE TITLE
Support for barcode scanner on android

### ISSUE THREAD

**Issue by jfmcarreira** [Forceu/barcodebuddy-android#5]
Would be possible to add support for bluetooth barcode scanners as input for this app?

Would be nice to have a portable interface for my scanner.

**Comment by Forceu** [comment]
Thank you for your feedback. That sounds like a good idea, does the scanner register as a keyboard?

**Comment by jfmcarreira** [comment]
Yes, on a notepad it shows as text input.

**Comment by Forceu** [comment]
Okay, so I tried implementing this feature. Please open the app, go to Settings and enable the option for the Barcode Scanner.

Then in the main menu scan a barcode with your scanner. Please let me know if it is working :)

[app-release.zip](https://github.com/Forceu/barcodebuddy-android/files/4536497/app-release.zip)

**Comment by jfmcarreira** [comment]
It worked nicely. Thank you

**Comment by Forceu** [comment]
Great to hear, thanks!
