### ISSUE TITLE
Feature Request: Set beep volume / vibration

### ISSUE THREAD

**Issue by noxhirsch** [Forceu/barcodebuddy-android#6]
Hi,
thank you for this Android App! It makes the scanning much easier :)

The volume of the scanning beep is very very loud if you accidentally have your phone set to max. volume. On the other hand, there's no beep when the media volume is turned off.
I don't think there's a way to ignore the media volume and send a beep in a set volume, right? But I think it would be useful to at least limit the volume in the settings of the app.
It would also be great, if you could enable a vibration feedback so that you know when an item is scanned if you either muted your media volume or don't want a beep at all.

**Comment by Forceu** [comment]
Thank you for your feedback! Added in https://github.com/Forceu/barcodebuddy-android/commit/14e0200c79868b51a09f20899caf7e57d729201d

**Comment by noxhirsch** [comment]
Wow, that was fast! Thank you very much!
