### ISSUE TITLE
Feature Request: Disable Display Rotation

### ISSUE THREAD

**Issue by noxhirsch** [Forceu/barcodebuddy-android#7]
Sorry for spamming! This is feature request nr. 2 of 3. I hope that's okay.

When scanning standard barcodes, the barcode has to be aligned with the red line. That sometimes mean, that you have to rotate your phone - but then it also rotates the display and you have to rotate more or back and rotate the item (if possible).
It would be cool to either limit the app to portrait or to have a setting for auto/portrait/landscape.

**Comment by Forceu** [comment]
Thank you for your feedback! Added in https://github.com/Forceu/barcodebuddy-android/commit/3f80b511df9e0f7e8a6076728bd5d1ba830bcfba
